server:
   port: 9090


keycloak:
    token:
      path: http://localhost:8080/realms/testrealm/protocol/openid-connect/token
    grant_type: password
    
spring:
  application.name: CLOUD_GATEWAY
  security.oauth2:
   resourceserver:
    jwt:
      jwk-set-uri: http://localhost:8080/realms/testrealm/protocol/openid-connect/certs
   client:
    provider:
      keycloak:
        issuer-uri: http://localhost:8080/realms/testrealm
    registration:
      keycloak:
        provider: keycloak
        client-id: testappkeycloak
        client-secret: DxIeI8x1mHPVLSGOj4qyNIVFohAqWtth
        authorization-grant-type: authorization_code
        scope: openid
        redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    gateway:
       default-filters:
           - TokenRelay
       routes:
         - id: CALLMESERVICE
           uri: http://localhost:8040
           predicates: 
             - Path=/callme/**          
        
        
        
        