server:
   port: 9090
   
spring:
   application: 
        name: 02-KEY-CLOAK-RESOURCE-SERVER
   security:
    oauth2:
      client:
        registration: 
           keycloak:
              client-id: testappkeycloak
              client-secret: DxIeI8x1mHPVLSGOj4qyNIVFohAqWtth 
              scope: openid,email,offline_access
              authorization-grant-type: authorization_code
        provider:
          keycloak:       
              issuer-uri: http://localhost:8080/realms/testrealm
   